type Document {
    id: ID!
    title: String!
    content: String!
    config: String
    type: String! # 'text' or 'sheet'
    workspace: Workspace!
    createdAt: String!
    updatedAt: String!
}

type DocumentVersion {
    id: ID!
    content: String!
    createdAt: String!
}

type Presence {
    userId: ID!
    email: String!
    documentId: ID!
    cursorOffset: Int
    cursorRow: Int
    cursorCol: Int
    cursorX: Float
    cursorY: Float
    isTyping: Boolean
    inHuddle: Boolean
}

type Message {
    id: ID!
    text: String!
    sender: User!
    documentId: ID!
    createdAt: String!
}

type WebRTCSignal {
    documentId: ID!
    senderId: ID!
    targetId: ID!
    signal: String!
}

type PublicDashboardPayload {
    dashboardDoc: Document!
    sourceDocContent: String!
}


extend type Query {
    documents(workspaceId: ID!): [Document]
    document(id: ID!): Document
    activeUsers(documentId: ID!): [Presence]
    documentVersions(documentId: ID!): [DocumentVersion]
    messages(documentId: ID!): [Message]
    publicDashboard(id: ID!): PublicDashboardPayload
}

extend type Mutation {
    createDocument(workspaceId: ID!, title: String!, type: String!): Document
    updateDocument(id: ID!, content: String, title: String, config: String): Document
    deleteDocument(id: ID!): Boolean
    restoreVersion(documentId: ID!, versionId: ID!): Document
    updatePresence(documentId: ID!, cursorOffset: Int, cursorRow: Int, cursorCol: Int, cursorX: Float, cursorY: Float, isTyping: Boolean, inHuddle: Boolean): Presence
    sendMessage(documentId: ID!, text: String!): Message
    sendWebRTCSignal(documentId: ID!, targetId: ID!, signal: String!): Boolean
}

extend type Subscription {
    documentUpdated: Document
    presenceChanged(documentId: ID!): [Presence]
    messageSent(documentId: ID!): Message
    webRTCSignalReceived(documentId: ID!, targetId: ID!): WebRTCSignal
}